### ISSUE TITLE
ISPF Client - Fatal: when changing branches

### ISSUE THREAD

**Issue by JHSpijker** [IBM/dbb#120]
When changing to a branch we get the following error

![image](https://user-images.githubusercontent.com/61826919/178659578-c0b212bd-f5f3-4d20-96f5-653c6109c468.png)

**Comment by donnellt** [comment]
@JHSpijker 

When performing an operation on a local branch, the branch name was not correctly set due to the assumption that the selected branch was a remote.  

Offending code segment in BGZBRANC REXX was:
```
Parse var BGZBRAN 'remotes/origin/'Branch
```
Update will include a set of the `Branch` variable if blank to the branch name extracted from the ISPF Table Variable `BGZBRAN` (i.e., local branch)

**Comment by donnellt** [comment]
Pull Request submitted - https://github.com/IBM/dbb/pull/166

**Comment by dennis-behm** [comment]
Delivered
