### ISSUE TITLE
Remove "** Build finished" text in groovyz

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb#158]
Hi,

The groovyz script shipped with DBB displays the message "** Build finished" on various occasions, in addition to displaying the return code.

However, we use groovyz for tasks other than building, such as deployment, using DBB APIs to make copies of USS to PDS, (unpacking a package in USS and feeding PDS from environments).

We believe that the groovyz script should be decoupled from the pure build function, and not display any message related to the build function.

The message "** Build finished" could be replaced for example by a message "** Run completed".

**Comment by dennis-behm** [comment]
Hi,

DBB is a utility to build mainframe applications. So `Build` does makes sense. But I understand your point, Denis. 

Because this is part of the IBM product and this repo is not used to track enhancement request - would you mind to open an idea on [https://ideas.ibm.com](https://ideas.ibm.com/products/6672764845844154062), please?

Thanks
Dennis

**Comment by dennis-behm** [comment]
I am closing the issue. If you created an idea on the IBM Idea portal for DBB, please let us know.

For some background into - the text `** Build finished` is required for some IDEs to understand when the a userbuild is completed.
